travis:
  secure:
    BINSTAR_TOKEN: tUGuHJIW83jfahPW8/W6SeQS+e7s210rtOx/Nljcr6SQ/zvK9+G5HZJQPbBs6iLFMzrjjhNbznch+SxkC5d5LTDr/VlnodGKzLTfFliFRyQw2rpjOVc7r0F50pmhtGDFmiSWsVPRrx+lek8qPEP9bUcqe12gv9y2JndCUA0cpYQMavaebOkazA5ok0pMK96zzytVh2/tz5UCT7isWHjl289dQX+csktQxKT2p9DnT5+hyhHohc6Zcnds0kU3z/7vEZyvrKCy2x5TLcJWHuxp1ZR+FlRKcbizu9/1qjjwQa4yGhV2MTHYh3uMaRszyHM/6GbuyF7l2CuOqBs5qYQ5+mjHHoludM2sfh/iUoRN9UZyKApcx6J2QAqAvw2pSI/TenbD5kpLu8fQgYhFilM3/Y2edTWLkgkOT7Yltr7xIdHoqDfcAVc+vQKfV2CY/SrMjpre9YOTQ7KTOxKY5LEgk6HuzCBh8WOoLOPHgKlH61gIlKmtrApSbSK+Mqzql/1h6i3lt5cCcGKxbUMvru+4Su6W94N8I91oLMEqpXvsvOzFbQSr9gdHKZvep7If2Sboyu/sW2lScoDabGBm5wFzJhh9NqHg5XIup+yPo5t9+ap4O1IFc2+9sK4/HDhMqYi4ULhWvUIPaVvHK3cGdJPJSJ6cDa1DPZhmHz/lPlL/KAU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
