travis:
  secure:
    BINSTAR_TOKEN: UpR6QToUmo26629E42VxWkB1tx1jx1jw3ASXRjjwVnZah5E1R4sM/agaTSZXbQBQ1LA+oV7BPOf4sfpqy0eznhsAyq5mc0fu+KMYf2NkD8CuPs2HWtVui+kODGenW9F9Y+xMyqfYB+nvZk96XxJwEf8sW0S+HGa8VF+ty3vbEaXMQyXCBgBUrD/aqlqB4vtjPLZPzsGL1kQgoARj2MSgqNFYCb0xQPxtEd/eYzcJ92x7xLSPSyOjnXTtH7cV8zbz4LSPHNxOBiAfwoDoqGSJSPS6hAi6b529+XkWWLKwTa7qgTOn8ScX6i0o1BV00pXL5LVT4vWsSBsPmTnkaIaAAGRR4NzFUghWadze287wZYWrbd1Ds4oQ7AMGqz3rwx8hrisfJxnHqSutcbPmiWuREEmn/jUQlzFtPANKeVy97YDP/NELi8fWfLbHsvtgoIV+j8gYBrjxdAelQ4KJGPlrLE50ORtv2dYzM7EpcDlzul19xkjZ9dsHPWqiDgQ+iQFXYTiei3zRja508r5ksvTIJ5rW22Y/y/U9kzJpcFcI2ugp1L4ZMB8PE/n8PmnJ9WcV9yrYGdhe/PuD8+UUIpvfP7s37xBhCZa4kjSk+H1mNkZQ83luBdmv2Ln2DgIf4ddguM+FgQ1/8KWpAAuMBW7cSA+dtLOoagUa0BYLko5R0Hw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
