travis:
  secure:
    BINSTAR_TOKEN: JTnAdmlzGd6P8KUaLYuStdY+DibwF26CXR9/5IrBZg4EqgmYxfG39BhmGQcaw7n68A/1hfj2ooQdzwq1qR1E5UgNFenHzKG4XphJJhpgPiyAwnx6pujnZKVurz69DuKYiYmM+0wK+9RL5prfeBTc5XN2cZqWalEoicKjkueXU0PROP9lVy0T/9PHCzqAdqr9cZ1l3m9fffmrF/Xn4yn6fs9jiZsmbnE2xBtAOZv5qgp5Ly1sMy8G5LbqvFLnKvFg01MSpE0whJevcTtok8x/p6asP6Gy3q2yogcp5PH7TH8FB6fuLWnnLu+YvgWL8ebgc26Gh95dcklxSPSIb0UMCTVXWBKtCAnpo3hLXfGVYDv3ybYdomuphMIoORX9/TNcF4v0J+671kX6Fs+X4HxC0vWk3y7efMVy4kY3tTwnwduXUAIPeEJKR/18wV/zxJuMGByVs1qC4VwqfWJk7Na688LRQDAswI3xXo4rPn7Kn8cNpTpkIbOrE2KdBtpI/iVTHTHtlBsvR7wZoPAws5WSO+r+VyG4W+D817FO+UiER6pNGMw9EGk+l4vJUBFElX6dJGDIJwuyENRmL/OdRPwM60BZvUmp50xKiohW5OHABzteyyqxKC5EqjT2GAswZ98k5gOWRceFsV6+hcVALDoE0mr5IoYQzqtwzJiVBWj5tRw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
